name: Java Tests

on:
  push:
    paths:
      - '**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [8, 11, 17, 21, 24]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Build and Test with Maven (${{ matrix.java }})
        run: mvn -B clean verify -Djava.version=${{ matrix.java }}
